blank_issues_enabled: true
contact_links:
  - name:❤️‍🔥Support❤️‍🔥
    url: https://t.me/theshivanshu
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://ultroid.tech/
    about: Basic documentation for setting up.
